source "https://rubygems.org"

gem 'cocoapods'
gem 'fastlane'

gem 'activesupport', '~> 7.0', '<= 7.0.8'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)

gem "fastlane-plugin-xcodegen", "~> 0.1.0"

gem "xcode-install", "~> 2.4"
